VAR FS=REQUIRE("FS");
CLASS FACTORY{
   CONSTRUCTOR(PATH){
    THIS.PATH=PATH;
    THIS.PARSE();
   }
   PARSE(){
      THIS.CONTENT=FS.READFILESYNC(THIS.PATH);

   }


}

MODULE.EXPORTS=(FUNCTION(){
    RETURN FUNCTION(PATH){
       RETURN NEW FACTORY(PATH)
    }
})()